openapi: 3.0.0
info:
  title: Book Tracker Service
  description: "This is the API definition for the Book Tracker Service."
  version: 1.0.0

servers:
  - url: http://localhost:3000

tags:
  - name: Booklists
    description: Create, view, and update booklists

  - name: Book
    description: View and add books to booklists

paths:

  /habitats:
    post:
      tags:
        - Habitats
      summary: Create a new booklist (AddHabitatLambda)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                habitatName:
                  type: string
                keeperManagerId:
                  type: string
                species:
                  type: array
                  items:
                    type: string
      responses:
        "200":
          description: A habitat object
          content:
            application/json:
              schema:
                type: object
                properties:
                  habitatId:
                    type: string
                  habitatName:
                    type: string
                  keeperManagerId:
                    type: string
                  totalAnimals:
                    type: integer
                  species:
                    type: array
                    items:
                      type: string
                  animalsInHabitat:
                    type: array
                    items:
                      type: string
                  acceptableEnrichmentIds:
                    type: array
                    items:
                      type: string
                  completedEnrichments:
                    type: array
                    items:
                      type: enrichment










