openapi: 3.0.0
info:
  title: Animal Enrichment Tracker Service
  description: "This is the API definition for the Animal Enrichment Tracker Service."
  version: 1.0.0

servers:
  - url: http://localhost:3000

tags:
  - name: Habitats
    description: Create, view, and update habitats

  - name: Enrichments
    description: View and add enrichments to habitats

  - name: Animals
    description: View, add, and remove animals from habitats

paths:

  /habitats:
    post:
      tags:
        - Habitats
      summary: Create a new habitat (AddHabitatLambda)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                habitatName:
                  type: string
                keeperManagerId:
                  type: string
                species:
                  type: array
                  items:
                    type: string
      responses:
        "200":
          description: A habitat object
          content:
            application/json:
              schema:
                type: object
                properties:
                  habitatId:
                    type: string
                  habitatName:
                    type: string
                  keeperManagerId:
                    type: string
                  totalAnimals:
                    type: integer
                  species:
                    type: array
                    items:
                      type: string
                  animalsInHabitat:
                    type: array
                    items:
                      type: string
                  acceptableEnrichmentIds:
                    type: array
                    items:
                      type: string
                  completedEnrichments:
                    type: array
                    items:
                      type: enrichment

  /habitats/{habitatId}:
    get:
      tags:
        - Habitats
      summary: Get an existing habitat (ViewHabitatLambda)
      parameters:
        - name: habitatId
          in: path
          description: ID of habitat to retrieve
          required: true
          schema:
            type: string
      responses:
        "200":
          description: A habitat object
          content:
            application/json:
              schema:
                type: object
                properties:
                  habitatId:
                    type: string
                  habitatName:
                    type: string
                  keeperManagerId:
                    type: string
                  totalAnimals:
                    type: integer
                  species:
                    type: array
                    items:
                      type: string
                  animalsInHabitat:
                    type: array
                    items:
                      type: string
                  acceptableEnrichmentIds:
                    type: array
                    items:
                      type: string
                  completedEnrichments:
                    type: array
                    items:
                      type: enrichment
        "500":
          description: "Invalid input parameters"
    delete:
      tags:
        - Habitats
      summary: Remove an existing habitat (RemoveHabitatLambda)
      parameters:
        - name: habitatId
          in: path
          description: ID of habitat to remove
          required: true
          schema:
            type: string
      responses:
        "200":
          description: A habitat object
          content:
            application/json:
              schema:
                type: object
                properties:
                  habitatId:
                    type: string
                  habitatName:
                    type: string
                  keeperManagerId:
                    type: string
                  totalAnimals:
                    type: integer
                  species:
                    type: array
                    items:
                      type: string
                  animalsInHabitat:
                    type: array
                    items:
                      type: string
                  acceptableEnrichmentIds:
                    type: array
                    items:
                      type: string
                  completedEnrichments:
                    type: array
                    items:
                      type: enrichment
        "500":
          description: "Invalid input parameters"
    put:
      tags:
        - Habitats
      summary: Update an existing habitat (UpdateHabitatLambda)
      parameters:
        - name: habitatId
          in: path
          description: ID of habitat to update
          required: true
          schema:
            type: string
      responses:
        "200":
          description: A habitat object
          content:
            application/json:
              schema:
                type: object
                properties:
                  habitatId:
                    type: string
                  habitatName:
                    type: string
                  keeperManagerId:
                    type: string
                  totalAnimals:
                    type: integer
                  species:
                    type: array
                    items:
                      type: string
                  animalsInHabitat:
                    type: array
                    items:
                      type: string
                  acceptableEnrichmentIds:
                    type: array
                    items:
                      type: string
                  completedEnrichments:
                    type: array
                    items:
                      type: enrichment
        "500":
          description: "Invalid input parameters"

  /habitats/{habitatId}/animals:
    get:
      tags:
        - Animals
      summary: Get a list of animals (ViewAnimalsForHabitatLambda)
      parameters:
        - name: habitatId
          in: path
          description: ID of habitat
          required: true
          schema:
            type: string
      responses:
        "200":
          description: A list of animals
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
    put:
      tags:
        - Animals
      summary: add an animal to animalsInHabitat (AddAnimalToHabitatLambda)
      parameters:
        - name: habitatId
          in: path
          description: ID of habitat
          required: true
          schema:
            type: string
        - name: keeperManagerId
          in: body
          description: ID of keeperManager
          required: true
          schema:
            type: string
      responses:
        "200":
          description: A list of animals
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
    delete:
      tags:
        - Animals
      summary: removes an animal from animalsInHabitat (RemoveAnimalFromHabitatLambda)
      parameters:
        - name: habitatId
          in: path
          description: ID of habitat
          required: true
          schema:
            type: string
        - name: keeperManagerId
          in: body
          description: ID of keeperManager
          required: true
          schema:
            type: string
      responses:
        "200":
          description: A list of animals
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /userHabitats:
    get:
      tags:
        - Habitats
      summary: Get a list of Habitats (ViewUserHabitatsLambda)
      parameters:
        - name: keeperManagerId
          in: query
          description: ID of keeper to retrieve habitats
          required: true
          schema:
            type: string
      responses:
        "200":
          description: a list of habitats
          content:
            application/json:
              schema:
                type: object
                properties:
                  habitatId:
                    type: string
                  habitatName:
                    type: string
                  keeperManagerId:
                    type: string
                  totalAnimals:
                    type: integer
                  species:
                    type: array
                    items:
                      type: string
                  animalsInHabitat:
                    type: array
                    items:
                      type: string
                  acceptableEnrichmentIds:
                    type: array
                    items:
                      type: string
                  completedEnrichments:
                    type: array
                    items:
                      type: enrichment










